name: enlp
channels:
  - defaults
dependencies:
  - python>=3.5
  - numpy=1.13.1
  - matplotlib=2.0.2
  - pandas=0.21
  - pytest=3.2.1
  - pytest-cov=2.5.1
  - nltk=3.3.0
  - spacy
  - pytest
  - Sphinx
  - numpydoc
  - scikit-learn
  - gensim
  - pip:
      - https://github.com/ohenrik/nb_dep_ud_sm/raw/master/nb_dep_ud_sm-0.0.1/dist/nb_dep_ud_sm-0.0.1.tar.gz
      - https://github.com/explosion/spacy-models/releases/download/en_core_web_md-2.0.0/en_core_web_md-2.0.0.tar.gz
      - pytest-runner
      - setuptools_scm
      - sphinx-rtd-theme
      - sphinx-gallery
      - nbsphinx
      - image
      - wordcloud
      - rake-nltk